version: '3.8'

services: 
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      #- "443:443"
    networks:
      - backend
    depends_on: 
      - php1
      # - php2
    volumes: 
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/mim.types:/etc/nginx/mim.types
      - ./proxy/proxy.conf:/etc/nginx/proxy.conf
      - ./proxy/fastcgi.conf:/etc/nginx/fastcgi.conf


  nginx1:
    image: nginx:latest
    expose:
      - "8080"
    networks:
      - backend
    depends_on: 
      - php1
    volumes: 
      - ./php1/www:/usr/share/nginx/html
      - ./nginx1/nginx1.conf:/etc/nginx/conf.d/default.conf

  php1:
    image: php:7.4-fpm
    expose:
      - "9000"
    networks:
      - backend
    volumes:
      - ./php1/www:/usr/share/nginx/html


  # nginx2:
  #   image: nginx:latest
  #   expose:
  #     - "8081"
  #   networks:
  #     - backend
  #   depends_on: 
  #     - php2
  #   volumes: 
  #     - ./nginx2/nginx2.conf:/etc/nginx/conf.d/default.conf

  # php2:
  #   image: php:7.4-fpm
  #   expose:
  #     - "9001"
  #   networks:
  #     - backend
  #   volumes:
  #     - ./php2/www:/usr/share/nginx/html


networks:
  backend:
    driver: bridge
