version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kms
      - web
  web:
    image: nginx:latest
    expose:
      - "8080"
    volumes:
      - ./source2:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.4-fpm
    expose:
      - "9000"
    volumes:
      - ./source2:/source

  kms:
    image: nginx:latest
    expose:
      - "8081"
    volumes:
      - ./source:/source
      - ./kms/default.conf:/etc/nginx/conf.d/default.conf
  phpk:
    image: php:7.4-fpm
    expose:
      - "9000"
    volumes:
      - ./source:/source
